
name: publish to gh-pages.

# main分支发生push触发
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai # 设置时区

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest # 虚拟机运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup nodejs.
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies.
        run: npm ci

      - name: Build src to generate dist.
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: Deploy; publish the dist to gh-pages.
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
